spring:
  application:
    name: AVAILABLE-SLOT-SERVICE

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/