spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/clinic
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: jsdlqwefkjaslfijFFDFdsffwe77

  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true

    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
