
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/clinic
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 

  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true

    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true

  application:
    name: USER
  cloud:
    config:
      uri: http://localhost:8888

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

project:
  title: User Service